[general]
import = ["~/.config/alacritty/themes/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[window]
blur = true
opacity = 0.9
startup_mode = "Maximized"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 12

[cursor]
style = { shape = "Block", blinking = "Always" }
