alias apt-update='sudo aptitude update'
alias apt-upgrade='sudo aptitude safe-upgrade -y'
alias apt-search='sudo aptitude search '
alias apt-install='sudo aptitude install '
alias cfg-vim='vim ~/.vim/vimrc'
