alias apt-update='sudo apt update'
alias apt-upgrade='sudo apt upgrade -y --auto-remove'
alias apt-search='sudo apt search '
alias apt-install='sudo apt install '
alias cfg-vimrc='vim ~/.vim/vimrc'
alias tailf='tail -f'
