#!/bin/bash

ICON_PATH="/usr/share/icons/Numix/24/status"

function get_volume {
 amixer -D pulse get Master | grep % | head -n1 | cut -d'[' -f2 | cut -d'%' -f1
}

function is_muted {
 amixer -D pulse get Master | grep '%' | awk '{print $6}' | grep off
}

function send_notification {
 VOLUME=$(get_volume)
 BAR=$(seq -s "-" $(($VOLUME/7)) | sed 's/[0-9]//g')
 if [ "$VOLUME" -eq 0 ]; then
  ICON="$ICON_PATH/audio-volume-low-zero.svg"
 else 
  if [ "$VOLUME" -lt 10 ]; then
   ICON="$ICON_PATH/audio-volume-low.svg"
  else 
   if [ "$VOLUME" -lt 30 ]; then
    ICON="$ICON_PATH/audio-volume-medium.svg"
   else 
    if [ "$VOLUME" -lt 70 ]; then
     ICON="$ICON_PATH/audio-volume-medium.svg"
    else 
     ICON="$ICON_PATH/audio-volume-high.svg"
    fi
   fi 
  fi
 fi
 if [ "$(is_muted)" ]; then
  ICON="$ICON_PATH/audio-volume-muted.svg"
  BAR=""
 fi
 notify-send "$VOLUME%"" ""$BAR" --icon=$ICON -t 1000
}

case $1 in
 up)
  amixer -D pulse set Master on -q 
  amixer -D pulse set Master 5%+ -q 
  send_notification
  ;;
 down)
  amixer -D pulse set Master on -q
  amixer -D pulse set Master 5%- -q
  send_notification
  ;;
 mute)
  amixer -D pulse set Master 1- toggle -q
  send_notification
  ;;
esac
