runtime! debian.vim
execute pathogen#infect()
syntax on

if has("autocmd")
 filetype plugin indent on
endif

if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

set background=dark
set sps=10
set incsearch		
set hlsearch		
set number
set sw=1
set iskeyword+=:
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
set spell spelllang=pt

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:vimtex_compiler_latexmk = {'callback' : 0}
let g:tex_flavor='latex'
let g:spell_auto_type='tex,doc,mail'
