runtime! debian.vim
execute pathogen#infect()
syntax on

if has("autocmd")
 filetype plugin indent on
endif

if filereadable("/etc/vim/vimrc.local")
  source /etc/vim/vimrc.local
endif

autocmd FileType latex,tex,text set spell spelllang=pt 

set background=dark
set sps=10
set incsearch		
set hlsearch		
set number
set sw=1
set iskeyword+=:
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
set rtp+=~/.local/lib/python2.7/site-packages/powerline/bindings/vim/
set laststatus=2
set t_Co=256
set tabstop=8 expandtab shiftwidth=4 softtabstop=4

set mouse-=a

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:vimtex_compiler_latexmk = {'callback' : 0}
let g:tex_flavor='latex'

hi clear SpellBad 
hi SpellBad cterm=underline,bold ctermfg=red 
