set nocompatible              
filetype off                  
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'easymotion/vim-easymotion'
Plugin 'jiangmiao/auto-pairs'
Plugin 'vim-syntastic/syntastic'
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'lervag/vimtex'
Plugin 'myusuf3/numbers.vim'
Plugin 'JamshedVesuna/vim-markdown-preview'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'valloric/youcompleteme'
Plugin 'itchyny/lightline.vim'
Plugin 'mattn/emmet-vim'
Plugin 'ryanoasis/vim-devicons'
call vundle#end()            
filetype plugin indent on    

syntax on
autocmd FileType latex,tex,markdown set spell spelllang=pt 

set encoding=utf-8
set background=dark
set sps=10
set incsearch		
set sw=1
set iskeyword+=:
set t_Co=256
set tabstop=8 expandtab shiftwidth=4 softtabstop=4
set mouse-=r
set laststatus=2
set showtabline=2 
set noshowmode 

set cursorline
hi CursorLine term=bold cterm=bold ctermbg=236
hi LineNr cterm=bold ctermfg=grey ctermbg=234

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0
let g:vimtex_compiler_latexmk = {'callback' : 0}
let g:tex_flavor='latex'
let vim_markdown_preview_github=1
let g:vim_markdown_folding_disabled = 1
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
let NERDTreeAutoDeleteBuffer = 1

hi clear SpellBad 
hi SpellBad cterm=underline,bold ctermfg=red 

nmap <Leader><Leader>n :NERDTreeToggle<CR>
