set nocompatible
filetype off
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/syntastic'
Plugin 'easymotion/vim-easymotion'
Plugin 'jiangmiao/auto-pairs'
Plugin 'scrooloose/nerdtree'
Plugin 'lervag/vimtex'
Plugin 'myusuf3/numbers.vim'
"Plugin 'valloric/youcompleteme'
Plugin 'ryanoasis/vim-devicons'
Plugin 'airblade/vim-gitgutter'
Plugin 'vim-airline/vim-airline'
Plugin 'vim-airline/vim-airline-themes'
call vundle#end()

" Vim configuration
filetype plugin indent on
syntax on
set encoding=utf-8
set background=dark
set sps=10
set incsearch
set sw=1
set iskeyword+=:
set t_Co=256
set mouse-=r
set laststatus=2
set showtabline=2
set tabstop=2
set shiftwidth=2
set expandtab
set noshowmode 
set cursorline
hi CursorLine term=bold cterm=bold ctermbg=236
hi LineNr cterm=bold ctermfg=grey ctermbg=234
hi clear SpellBad 
hi SpellBad cterm=underline,bold ctermfg=red 
autocmd FileType latex,tex,markdown set spell spelllang=pt,en

" Syntastic Configuration
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" Vimtex Configuration
let g:vimtex_compiler_latexmk = {'callback' : 0}
let g:tex_flavor='latex'
if !exists('g:ycm_semantic_triggers')
  let g:ycm_semantic_triggers = {}
endif
let g:ycm_semantic_triggers.tex = g:vimtex#re#youcompleteme

" NERDTree Configuration
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
let NERDTreeAutoDeleteBuffer = 1
nmap <Leader><Leader>n :NERDTreeToggle<CR>

" Airline Configuration
let g:airline_theme='powerlineish'
let g:airline#extensions#tabline#enabled = 1

"Custom Maps
nnoremap <Leader>o o<Esc>
nnoremap <Leader>O O<Esc>
