#!/bin/bash

### BEGIN INIT INFO
# Provides:          aplocal-wifi
# Required-Start:    $all                               
# Required-Stop:                                        
# Default-Start:     2 3 4 5                            
# Default-Stop:      0 1 6                              
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

case "$3" in
	start)
		nmcli r wifi off
		rfkill unblock all
		#ifconfig $1 down
		ifconfig $1 up 10.0.0.1 netmask 255.255.255.0
		sleep 2
		service isc-dhcp-server start 
		sleep 2
		service firewall start
		service hostapd start
		sysctl -w net.ipv4.ip_forward=1
	;;
	stop)
		ifconfig $1 down
		service isc-dhcp-server stop
		service hostapd stop
	;;		
        restart) 
	       $0 $1 $2 stop
	       $0 $1 $2 start
	;;
	*)
		echo "Sintaxe: $0 [wlan interface | eth interface] [start | stop | restart]"			
	;;
esac
